import type { Metadata } from "next";
import { Inter, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "../components/providers"

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const plexMono = IBM_Plex_Mono({
  variable: "--font-plex-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * The root HTML layout for the application that wraps page content with global fonts and the Convex client provider.
 *
 * @param children - The page content to render inside the document body.
 * @returns The top-level HTML element containing a body with global font classes and the ConvexClientProvider.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

      <html lang="en" suppressHydrationWarning>
          <body
            className={`${inter.variable} ${plexMono.variable} antialiased`}
            >
            <ConvexClientProvider>

              {children}
            </ConvexClientProvider>
          </body>
      </html>
  );
}